### ISSUE TITLE
Add support to see ACs by features to approbation (pt1)

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/approbation#109]
## Issue:

Now that we are delivering feature iteratively during milestones and the fact that acceptance criteria for a single feature may span across multiple spec files, it is becoming increasingly difficult to be able to get an accurate picture of the test coverage by feature.

Having had a few discussions on this we think the best approach for now is:

- Add support for a `features.json` file like we have for the categories 
- Add support for the approbation run to output a feature table view as we have for categories 
- Have a CI check on new PRs to check that any AC added or updated belongs to a feature

### Additional info:

- It is possible that a single AC may span multiple features (at least for older ACs)

**Comment by edd** [comment]
Closed by #113
