### ISSUE TITLE
Categories for user-interface Acceptance criteria

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/approbation#48]
I request the following changes so that the team can have a regular output of what tests have been written in the [FE mono repo](https://github.com/vegaprotocol/frontend-monorepo) against the [front end acceptance criteria](https://github.com/vegaprotocol/specs/tree/master/user-interface#user-interface-acceptance-criteria).

- [x] remove the [hard coded categories](https://github.com/vegaprotocol/approbation/blob/main/src/lib/category.js#L2), and pick them up from JSON in the Specs repo. This [PR adds](https://github.com/vegaprotocol/specs/pull/1263) JSON categories to the root of `/protocol` and `/user-interface`
- [ ] Make any other changes required for this script to be run whenever a PR is raised in FE mono repo
- [ ] update this https://github.com/vegaprotocol/devops-infra/issues/1476 for ops to implement 

This aim is to get to a point where we can have an output like this ([spreadsheet](https://docs.google.com/spreadsheets/d/1zQQFYXWwnYeg0f5G2FsjZHuXW3OC9wni5ZhDr473GDY/edit#gid=617178205)):
<img width="1017" alt="Screenshot 2022-09-26 at 18 15 00" src="https://user-images.githubusercontent.com/13255539/192339750-336badb8-527c-4014-8fca-9bf146927bd2.png">

I'm not sure if this means that this script needs to run for each App in the mono-repo.
or if the [apps.js](https://github.com/vegaprotocol/specs/pull/1263/files#diff-28e95640eb9b1b76037f49b9f043bbccf8367e43c52b86b8fade301594a360f5) file can be used to create the columns.

note: the FE Acs have must, could and shoulds. for now this script can ignore it. and we'll de-scope the requirement for these to be covered by commenting out the codes.

**Comment by JonRay15** [comment]
All looks good to me ... my only petty comment would be I'd prefer we display the text as 

ACs Covered / Total ACs  (%age) 

Currently its the other way around in your first example.

Other than that I think it looks good and yes Calum and I will have to write some stuff for some of these.

**Comment by JonRay15** [comment]
Also how are we pulling in the "AC Doneness"?

Or is that something we add manually afterwasrds?

in the core report I swap out the automatically generated part each week and maintain the static commentary.  not the most glamourous job but its simple enough,.

**Comment by edd** [comment]
I reckon `apps.json` will be able to do some of what we need. What's not clear is how you'd map what we have now on to the spreadsheet in terms of *target* coverage. I can imagine how to say these apps should cover this whole file, but now how Wallet should cover 2 out of 30, and console should cover 28/30. That 'Wallet should cover 2 of these' isn't there, and to make it in the current style we'd need to do something like `app.json` but listing each criteria, which sounds tedious?

I'm going to assume that knowing that Wallet and Desktop Wallet should both be judge against their coverage of *all* wallet related UI requirements, given that I'm nearly stopping for the day anyway. If that's a bad assumption, let me know.
